### PR TITLE
New feature: load balancing

### PR DESCRIPTION
**Pull request by blu3mania**
Also minor performance tweaks:

1. Avoid using Array.includes which is O(n)
2. Avoid unnecessary conversions between Array and Set
3. During startup, start setting up fixed rooms while collecting dynamic rooms instead of waiting for that task to be performed first.
4. When filtering dynamic rooms, also exclude those already connected in DynamicController

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
Great proposals, but there're several design considerations here in regard of distributing the monitoring task to multiple servers:
1. The central server must assume the responsibility of assigning rooms to its child servers to monitor, and it is important that child servers don't receive duplicated rooms (if one already listens on one room, then the other shouldn't). 
2. The child servers need to report back to the server whenever it receives gift-related messages, and upon receiving such messages, the central server needs to verify the integrity of the message.
3. Since the rooms update periodically, preventing duplicate monitoring is quite involved, and frequent communication between the child servers and the central server is required to sort out which server listens on which rooms.

I might be mistaken, but is the current design filtering out rooms without assigning them to child servers? Note that simply running two copies of this program (with indexing) will not guarantee each copy to listen to half of the rooms gathered, since the sorting of dynamic rooms is inconsistence at best and completely random at worst. To balance the load, communication between the central server and the child servers is inevitable. I've been avoiding multiserver monitoring precisely for this reason—management overhead is much greater than the benefits gained (2% additional coverage?). But again, I might be misunderstanding the goal of the load balancing here, please correct me if I did.

Other than that, the optimization on Set over Array is great.

**Comment by blu3mania** [comment]
I kind of explained (though might be vague) in the updated README.md. The algorithm is based on room number % total servers, so there won't be conflicts between servers. I think even in the case when a room gets assigned a short-number alias the query still returns the original room number which doesn't change.

Yes, it's not a master/slave based design so the loads are not totally balanced, but should be quote close. Besides, even if multiple servers have the same number of rooms monitored, the load will likely not be same anyway due to different level of activities in each room.

**Comment by Billyzou0741326** [comment]
Dynamic rooms are obtained from the API, and servers retrieve rooms from that API at different times (even if the programs launch at the same time). The uncertainty on the ordering of those rooms also means it's likely that (server 1's dynamic + server 2's dynamic + … + server n's dynamic) <= one-request-for-dynamic-rooms. This is the concern here, since there isn't one origin of truth (central server) to distribute the rooms.

**Comment by Billyzou0741326** [comment]
If such inconsistency is acceptable, I suggest extending a `RoomDistributor` to override the `RoomCollector`'s get functions to perform the filtering.

**Comment by blu3mania** [comment]
I am not sure I follow what you are saying. Let's assume there are 2 servers, so one monitoring odd room IDs and one monitoring even room IDs. Dynamic rooms are retrieved every 2 minutes. Say the server monitoring even numbers is always one minute behind the other one. At time 0 minute, odd-number server retrieves dynamic rooms, and have 10000 rooms returns, out of them 5300 are even and only 4700 are odd, which are monitored by this server. At time 1 minute, even-number server queries for dynamic rooms and now get 12000 rooms, and 6400 are even, which are now monitored by this server. Yes, there are 900 new odd-number rooms (5600-4700) that are not monitored by the other server (yet) however, at time 2 minute, those rooms (if still live) will be retrieved by odd-number server and monitored.

The even/odd number check is based on a room's ID which, unlike the index returned from query, shouldn't change, so all odd number room IDs will be monitored by server 1, and all even number room IDs will be monitored by server 2, up to a delay of 2 minutes. This is not worse than current single server design, and there is no overhead in communication between the 2 servers.

**Comment by blu3mania** [comment]
Sure, a derived class sounds like a good idea. If you are ok with the fundamental design, I can work on adding this new class.

**Comment by blu3mania** [comment]
FYI, when I tested in local EST at around 16:40, these were the number of rooms monitored by 2 servers:

[2020-02-23 16:41:39]   Monitoring (静态) 2586 + (动态) 1199 <-- even-number server
[2020-02-23 16:41:56]   Monitoring (静态) 2724 + (动态) 1193 <-- odd-number server

**Comment by Billyzou0741326** [comment]
The interval might not be exactly two minutes, because `awaiting` reponses from bilibili's API may take longer than expected, especially when `http request aborted` (timeout) occurs (not uncommon for me). Also, if two consecutive requests to the API come back with inconsistent ordering of roomids (not likely but this is uncertainty, again), then even/odd results in duplicating and missing rooms. 

For this reason, I'm inclined to stick to single-server design. Are there any compelling reasons to go for multi-server deployment?

**Comment by blu3mania** [comment]
I understand that it will never be a perfect 2-minute query interval, but the key factor here is that rooms are physically divided into different servers, and there are no conflicts by design, so essentially each server is monitoring its own subset of rooms, and the performance of other servers won't affect how many rooms it monitors, so the coverage of all servers should be the same as a single server.

I don't think at the moment there is really a compelling reason to go with multi-server. It's mainly to make Windows servers more usable as when it's close to 20000 rooms on one server it's pushing the limit of Windows. Even for Linux servers, when there are more than 60000 rooms then it has to be divided (yes, I know it will take quite a while for that to happen, or never...).

**Comment by blu3mania** [comment]
And to clarify again, the filtering is based on room ID, which doesn't change between queries, regardless of query order, or if new rooms have been added in between rooms queried previously.

**Comment by Billyzou0741326** [comment]
Most clients aren't designed to take inputs from multiple servers. Splitting servers will make it quite infeasible to configure this program for serving other client programs. 

Keeping the number of rooms under 20000 is good enough, in my opinion. Unless that last 2% of coverage is really desired. Instead of going for more connections and risk stability, I favor providing an option to suppress # of rooms—suppress fixed rooms, preferably. Personally I've been filtering out rooms inactive for 4 days or more, instead of 30 days, in order to keep the CPU usage under a certain level. 

By keeping this project a single-server program, we reserve the ability to match with other clients. By matching the broadcast format with existing clients, we may get away without having to maintain the client. So, instead of providing the functionality of splitting servers, how about we keep it a single-server program and add an option to suppress connections?

**Comment by blu3mania** [comment]
I want to mention that it's an optional feature and by setting total servers to 1, it runs in a single server exactly like current code (well, there is one extra check when rooms are queries so not exactly, but if we create derived controllers and make the decision at startup time then it would be exactly the same), and it will still be compatible with other clients.

I do see better network performance on Windows when splitting load this way, as there seem to be fewer dropped connections. Though, I guess I might be the only one who runs monitor on Windows, so if you don't feel the need I can understand. I don't want to sound like I am passing you to take it.

As for controlling number of rooms, I don't know if there will be a simple solution. Reducing inactivity time check results in fewer fixed rooms, but not dynamic rooms. Bilibili is trying to get their live business boosted. I am not sure if they will be successful, but if they manage to double their number of signed hosts, dynamic room query could result in more than 20000 rooms. It will require certain complicated algorithm to cut down the list.

**Comment by Billyzou0741326** [comment]
I see the reasons for splitting servers now. Cut down # of connections or extend to a robust multi-server design, going forward I'll have even less time for this project. Whatever changes made to it, so long as it remains maintainable and object-oriented, then I'll take it. For now, I suggest deriving `RoomDistributor` from the `RoomCollector`, and in *App*'s constructor simply use 
```javascript
if (config.loadBalancing.totalServers > 1)
    this._roomCollector = new RoomDistributor();
else
    this._roomCollector = new RoomCollector();
```

**Comment by blu3mania** [comment]
That's a great suggestion. I will actually name it SimpleLoadBalancingRoomDistributor in case that in the future we have the need for a more sophisticated load balancing solution. I will also add a new method there (getRaffleRoomsInArea) so I can delegate the logic from RaffleController to it.

Will let you know once I commit. Thanks.

**Comment by blu3mania** [comment]
@Billyzou0741326 Refactored code checked in. Thanks.

**Comment by Billyzou0741326** [comment]
Windows seems to handle 2w connections without any problems, on my end at least.
I configured the `TcpTimedWaitDelay` to 2 seconds and available port range from 1025 upward 64511.

Capture

**Comment by blu3mania** [comment]
Hmm, it does seem I was too quick to blame Windows. If I run both servers on 2 Windows machines at the same time they start to experience the same connection drops after a while, even though if I only run one server it behaves much better (there are still drops but way less). Also it seems that Windows may have some issues with FIN_WAIT_2 state. Though Microsoft claims that these connections have a 4 minute timeout by default, some of them got stuck forever. I had to use TCPView to close them. So, it suggests that the issue may be at my router or even the internet connection itself.

I will think of ways to limit the # of connections. One idea is to query by "online" instead of "live_time" and take the first n results, then compare established connections against the result to drop those not in the result, followed by current logic to add those from result that are not connected yet. One issue about this approach is that "online" value gets affected mainly by gift values instead of real user count, so when someone suddenly gets even a small gift, like CALL, his rank could raise quite a lot, causing the query result very versatile near the bottom. When the effect of gift wears off, that room will drop in rank as it now mainly relies on online user count again. This could lead to frequently dropping rooms only to add them back later on after another query.

**Comment by Billyzou0741326** [comment]
That was unfortunate. I ran it over the night and survived without obvious problems. 

Many types of gift rely on monitoring as many dynamic rooms as possible (i.e maps, pk, storm). We're better off not going into raffle prediction. If we only listen on selected rooms, coverage will drop anyways, so might as well not worry too much about filtering.

**Comment by blu3mania** [comment]
> That was unfortunate. I ran it over the night and survived without obvious problems.
> 
> Many types of gift rely on monitoring as many dynamic rooms as possible (i.e maps, pk, storm). We're better off not going into raffle prediction. If we only listen on selected rooms, coverage will drop anyways, so might as well not worry too much about filtering.

I know. Though, with the limit I am facing, monitoring half the rooms still give me better coverage than what I had in the past, when the server was essentially dropping most of connections all the time. I suspect most of the issues encountered in the past were due to failed health check since it encountered tons of ECONNRESET and ETIMEDOUT. This server is just a fail-safe backup, so my primary goal is to keep it usable, and after that, try to get more coverage. I think I will still try to entertain the idea of a shaved list just for fun, and see where it goes. Likely won't commit even if it works, or just keep it in a branch...

**Pull request merged**
