### PR TITLE
Raffle data building code refactoring, and more

### PR DESCRIPTION
**Pull request by blu3mania**
1. Refactored raffle data classes to have a common base Raffle class.

- Clients mostly only deal with Raffle, so there is no need to use union types.
- Didn't define an interface since these classes are just data containers, not really entities that share common behavior. For example, to deal with Anchor, client will need to cast from the base Raffle class.
- Provided an exported array for supported raffle categories.
- As a result, these also enabled to have common data handling in various clients. For example, HTTP server now supports viewing all categories.
- Removed builders and just let data container classes generate the data needed when requested. For WS broadcast, toJson() is used (anchors are still blocked). For HTTP server, convert() is provided for backward compatibility (though, I am not sure if there are clients relying on current HTTP server JSON format so this conversion may not be needed).
- As such, renamed the file as raffle.ts (in a separate commit, so commit d2889b6 still shows  changes in this file before being renamed).

2. Refactored Controller classes

- Abstract class GuardController no longer needs to check for concrete derived classes.

3. Added access modified in touched classes

- Mainly to define protected and private methods when they are not meant to be public.
- Didn't modify all other classes.

4. Other changes

- Use LF as newline style in compiler output to maintain consistency between Windows and Linux.
- Added abstract keyword for classes that are not meant to be instantiated.
- Modified some methods defined in various abstract classes to be abstract, if it's not meaningful to provide a default implementation.
- Exported TCPAddress interface from config.ts to avoid re-defining it in other places.

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
The refactoring looks great, though some of my newer commits are introducing conflicts and preventing the merge. If you can please apply these changes to the latest commits, that would be awesome. Thank you!

On another note, would it be better to use `enum`s rather than strings to represent the raffle types?
```javascript
enum RaffleCategories {
    Gift = 'gift',
    Guard = 'guard',
    PK = 'pk',
    Storm = 'storm',
    Anchor = 'anchor',
}
```

Otherwise all looks great. If you prefer, I can apply these changes on my end, though that will undermine your contributions, so it'd be great if you can do it instead. 
Sorry for asking too much :(

**Comment by blu3mania** [comment]
RaffleCategories was introduced mainly just for looping so I used array, but I agree, enum is better from language perspective. I am outside at the moment. Will merge your new commit and make this change tonight.

**Comment by Billyzou0741326** [comment]
That'll be awesome, thanks!

**Comment by blu3mania** [comment]
@Billyzou0741326  Merged and updated. Though, even with string enum, iterating over it is still a pain as it's not a feature that the underlying JS natively supports. There are hacks to make it possible but I generally dislike hacks... Anyway, I ended up using lowercase keys to match the string values in the enum to workaround it. Not elegant, but at least I don't need to use hacks. :)

**Pull request merged**
