### PR TITLE
Fixed the issue that new fixed rooms are not saved, by not overwriting in-memory map with database file

### PR DESCRIPTION
**Pull request by blu3mania**
Also improved performance by only loading database file once during startup. It still allows replacement of the db file during execution by monitoring the file.

Added graceful shutdown when CTRL-C is pressed.

Added access modifiers in config.ts which were missed in last commit.

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
Loading before every `save` operation is intentional. I might want to substitute out the record during execution. Performance problem is trivial O(N) for under 60k items per two min. 

Just let it abandon rooms collected in the recent two minutes, these are not important data. Recent model is complex enough

**Comment by blu3mania** [comment]
Hmm, if you do that, you are overwriting the in-memory room data and no new rooms collected will be saved at all. If substituting out room data during execution is desired, you may want to detect file change instead of always loading and overwriting in-memory map.

**Comment by Billyzou0741326** [comment]
I see the concern (scared me), just checked...
104 to 106 is the highlight

https://github.com/Billyzou0741326/bilibili-live-monitor-ts/blob/f9456d6a5ef4ab44b292c4b95f4d0693e6dbfb84/src/db/database.ts#L97-L106

**Comment by blu3mania** [comment]
No, the problem happens after load(), actually at line 40.

**Comment by Billyzou0741326** [comment]
The logic here is, any rooms in the database but not in the map will be added. Otherwise, leave existing rooms in the map untouched

**Comment by Billyzou0741326** [comment]
That is indeed the problem

**Comment by Billyzou0741326** [comment]
One of my recent commits introduced this problem, an earlier version looked like this:
https://github.com/Billyzou0741326/bilibili-live-monitor-ts/blob/76bbba4fe617bd5f668f9b2b8e95c77d7b17c35d/src/db/database.ts#L29-L36

**Comment by blu3mania** [comment]
Yeah, I saw the history... We at least need to fix that part, and I'd still say that if substituting out room data during execution is desired, you may want to find a better way than loading the file back every 2 minutes. After all that scenario shouldn't happen very often.

**Comment by blu3mania** [comment]
This API seems to be perfect for the job: https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener

**Comment by Billyzou0741326** [comment]
On saving to database, the watcher will be notified too. I think the fs watcher is perfect for config files (a potential consideration, watching for `settings.json`?), but might not work well with files that the program directly writes to unless there's a way to distinguish the process that made the modification.

**Comment by blu3mania** [comment]
Can be resolved by something like:
```
    private save(): Promise<void> {
        const data: string = JSON.stringify(this.filter(this._roomData), null, 4);
        this._watcher.pause();
        return new Promise((resolve, reject) => {
            fs.writeFile(this._filename, data, (error: any): void => {
                if (error) {
                    reject(error);
                } else {
                    //cprint('Database: fixed room info saved.', chalk.yellow);
                    resolve();
                }
            })
        }).then(this._watcher.resume());
    }
```

**Comment by Billyzou0741326** [comment]
Then we'll need to roll out the implementation of resume and pause. Or is there already an official implementation that I missed?

**Comment by blu3mania** [comment]
No, we need to write it ourselves... I can try to come up with an impl, test it and update this PR.

**Comment by Billyzou0741326** [comment]
If it turns out too overwhelming, don't worry about it. I'm convinced to take out `load` before `save`.

**Comment by blu3mania** [comment]
Shouldn't be too hard. I already coded it up, just need to test.

**Comment by blu3mania** [comment]
It is working. Though, on Windows whenever the file is changed, by copying over another copy, or modified in a text editor, it receives 3 "change" events. I need to find out why. Meanwhile, if you want I can commit the change so you can try on Linux to see if it behaves better,

**Comment by Billyzou0741326** [comment]
If it's showing signs of undefined behaviors, let's not rely on that. 

Another design: 
1. Before saving, `fs.statSync(this._filename)`, take the `mtimeMs` in the return value
2. if it doesn't match the previous `mtimeMs`, load
3. Save, then update `fs.statSync(this._filename)`

**Comment by blu3mania** [comment]
It seems to be a well known Windows issue: https://github.com/nodejs/node-v0.x-archive/issues/1970#issuecomment-2599352
I solved it by using a 10ms DelayedTask. The delay is arbitrary but 10ms shouldn't be a big deal. I will commit the change with debugging cprint in place (but commented out) so you can take a look.

**Comment by blu3mania** [comment]
@Billyzou0741326 PR updated.

**Comment by blu3mania** [comment]
Done. Also removed those cprint as it seems quite stable.

**Comment by Billyzou0741326** [comment]
I want to take away the async save on Ctrl-C. To me graceful shutdown is discontinuing all activities right on the point, when the program crashes or when the user decides to stop. Nothing critical will be lost, kust let it abandon all rooms

I'll make a few changes then merge the pr

**Pull request merged**
