### PR TITLE
Enhancement: optional user authentication support

### PR DESCRIPTION
**Pull request by blu3mania**

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
I'm quite hesitant to use url-based authentication. What I have in mind is a full fledged per-user key authentication system stored in a database of some kind, the implementation of which is quite involved. 

For now let's leave out the whole authentication part, and perhaps come back to it later.

**Comment by blu3mania** [comment]
Sure. In that case I will create a new feature branch and make a PR from there so we can leave it open. After that I will close this one and rebase my master branch back to the same as your HEAD commit.

**Comment by blu3mania** [comment]
As mentioned, a new feature branch "feature/user-auth" was created and a new PR from that branch. This PR is thus closed.

**Comment by Billyzou0741326** [comment]
Sounds good!

I'm thinking of having the client send the verification info after the connection is established. Beyond that, I'm not sure how to design the authentication process, unfortunately,

**Pull request closed without merging**
