### PR TITLE
Make room collector strategy configurable

### PR DESCRIPTION
**Pull request by blu3mania**
Expiry in database; Dynamic rooms query interval, page size and sort type.

Also various changes:

- Improved performance when adding rooms to a monitor by skipping creation of Set which is not needed.
- Made GuardController's listener 'close' handling better in OOP.
- When querying dynamic rooms, only add extra page when querying all rooms.
- Include error message in HTTP error
- Display timeout instead of aborted when HTTP request times out

### CODE REVIEW

**Comment by Billyzou0741326** [comment]
`git rebase -i HEAD~4`    // squash 4 commits into 1

In the text editor that comes up, replace the words "pick" with "squash" next to the commits you want to squash into the commit before it. Save and close the editor, and git will combine the "squash"'ed commits with the one before it. Git will then give you the opportunity to change your commit message to something like, "Issue #100: Fixed retweet bug."

`git push origin branch-name --force`    // must force push to resolve conflicts

`git commit --amend`    // You can always edit your commit message

Full text available at
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by Billyzou0741326** [comment]
Great, I'll review the changes once I find time. Thanks!

**Comment by blu3mania** [comment]
Thanks Bill. :)

**Comment by Billyzou0741326** [comment]
I noticed some components are becoming tightly coupled in recent commits. For instance, RoomCollector and Database now requires configuration to be usable, meaning that we'll have to remember that we need to give the constructor a Strategy to create an object of those classes. This is likely an antipattern. Since we're not writing libraries (lol), we might want to minimize the number of configurations open to users. Note that for `dynamicRoomsPageSize`, we know the valid range and the best value for it, but the user can mess this up easily. I suggest leaving this out. The same if true for `dynamicRoomsSortType`. 

In my next commit after merging, I plan to: 
1. Make the parameters for `RoomCollector` and `Database` optional
2. Remove `dynamicRoomsSortType` and `dynamicRoomsPageSize` from the config

Are you ok with these?

**Comment by blu3mania** [comment]
I am fine with them. They are more for debugging purpose and I agree most won't even touch them.

**Comment by Billyzou0741326** [comment]
Awesome

**Comment by blu3mania** [comment]
@Billyzou0741326  Just saw your new change and noticed that the calculation of expiry is in hours, not days.

**Comment by Billyzou0741326** [comment]
Ouch

**Pull request merged**
